INCLUDE Crouching.ink
INCLUDE FirstJump.ink
INCLUDE FirstBloom.ink
INCLUDE LongJump.ink
INCLUDE Sprinting.ink
INCLUDE StateChange.ink
INCLUDE TheFlower.ink
INCLUDE TheWall.ink
INCLUDE TipForFlower.ink
INCLUDE PokemonStory.ink